### ISSUE TITLE
Enhancement: Release -> Tweet

### ISSUE THREAD

**Issue by dschier-wtd** [whiletruedoio/tooling#1]
As a product owner, I want to inform twitter followers about new releases of repositories, so they can see it in the timeline.

Acceptance Criteria:

- each new release triggers a tweet
- optional customizable text
- free for open source / github public repositories
- saas solution

Deliverables:

- New document created describing the solution
- PoC repo created to demonstrate behavior
- account created or requested (support via @daniel-wtd )

References:

- automate.io (has an app for github)
- zapier.com (already used to push blog posts)

**Comment by daniel-schier** [comment]
zapier.com and automate.io also have integrations for slack

**Comment by daniel-schier** [comment]
Zapier does not support tags, but only GitHub releases and you need one action per repository :/

**Comment by daniel-schier** [comment]
automate.io has the same limitations... meh

**Comment by pdq21** [comment]
How about [Send Tweet Action](https://github.com/marketplace/actions/send-tweet-action)? Maybe replace `on: [push] ...` with
```
on:
 release:
  type[s]: [published[,created,edited]]
  tags:
   - tag A
  jobs:
   tweet:
    runs-on: ubuntu-latest
    steps:
     - uses: ethomson/send-tweet-action@v1
      with:
       status: "We proudly present release ${{ github.ref }} with tag ${{ github.event.release.tag_name }}."
       ...
```
Did you have a look at [Integromat's GitHub App](https://www.integromat.com/en/help/app/github)? It also does not appear to look at tags of new releases.
Unfortunately there seems to be no free tier for [MS PowerAutomate](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq) despite Actions running on Azure Pipeline.
